name: student

services:
  web:
    build: .
    image: custom-php-flight
    container_name: php_student
    volumes:
      - ./backend/src:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql_student
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: student
      MYSQL_USER: student
      MYSQL_PASSWORD: student
    volumes:
      - db_data:/var/lib/mysql
      - ./itu.sql:/docker-entrypoint-initdb.d/itu.sql:ro
  
  vue:
    image: vuejs-vuejs:latest
    container_name: vue_student
    working_dir: /app
    volumes:
      - ./frontend:/app
    command: >
      sh -c "npm install && npm run dev -- --host"
    ports:
      - "5173:5173"

volumes:
  db_data: